<?php

namespace AppBundle\Repository;

/**
 * FavoriteFarmerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteFarmerRepository extends \Doctrine\ORM\EntityRepository
{
}
