<?php

namespace AppBundle\Repository;

/**
 * FavoriteAnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteAnimalRepository extends \Doctrine\ORM\EntityRepository
{
}
