<?php

namespace AppBundle\Repository;

/**
 * OwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($name)
    {
        return $this->getEntityManager()->createQuery(
            "SELECT o FROM AppBundle:Owner o WHERE o.name LIKE '%".$name."%'"
        )->getResult();
    }
}
