<?php

namespace AppBundle\Repository;

/**
 * PaymentBasketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentBasketRepository extends \Doctrine\ORM\EntityRepository
{
}
