<?php

namespace AppBundle\Repository;

/**
 * RecipeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecipeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByName($title)
    {
        return $this->getEntityManager()->createQuery(
            "SELECT o FROM AppBundle:Recipe o WHERE o.title LIKE '%".$title."%'"
        )->getResult();
    }
}
