<?php

namespace AppBundle\Repository;

/**
 * TypeAnimalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeAnimalRepository extends \Doctrine\ORM\EntityRepository
{
}
