my_user:
    resource: "@MyUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

app_main:
    resource: '@AppBundle/Resources/config/routing/main.yml'

app_add:
    resource: '@AppBundle/Resources/config/routing/add.yml'
    prefix: /add/

app_basket:
    resource: '@AppBundle/Resources/config/routing/basket.yml'
    prefix: /basket/

app_blog:
    resource: '@AppBundle/Resources/config/routing/blog.yml'
    prefix: /blog/

app_explore:
    resource: '@AppBundle/Resources/config/routing/explore_.yml'
    prefix: /explore/

app_favorite:
    resource: '@AppBundle/Resources/config/routing/favorite.yml'
    prefix: /favorite/

app_message:
    resource: '@AppBundle/Resources/config/routing/message.yml'
    prefix: /message/

app_modify:
    resource: '@AppBundle/Resources/config/routing/modify.yml'
    prefix: /modify/

app_product:
    resource: '@AppBundle/Resources/config/routing/product.yml'
    prefix: /product/

app_profile:
    resource: '@AppBundle/Resources/config/routing/profile.yml'
    prefix: /profile/

app_search:
    resource: '@AppBundle/Resources/config/routing/search.yml'
    prefix: /search/