security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_OWNER:       ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/add*, role: ROLE_USER }
        - { path: ^/add/product$, role: ROlE_OWNER }
        - { path: ^/add/blog$, role: ROlE_ADMIN }
        - { path: ^/add/news$, role: ROlE_ADMIN }
        - { path: ^/basket*, role: ROlE_USER }
        - { path: ^/favorite*, role: ROlE_USER }
        - { path: ^/message*, role: ROlE_USER }
        - { path: ^/modify*, role: ROLE_USER }
        - { path: ^/modify/product$, role: ROlE_OWNER }
        - { path: ^/modify/blog$, role: ROlE_ADMIN }
        - { path: ^/modify/news$, role: ROlE_ADMIN }
        - { path: ^/profile/myproducts$, role: ROLE_OWNER }
