add_blog:
    path: "blog/"
    controller: "AppBundle:Add:blog"

add_product:
    path: "product/"
    controller: "AppBundle:Add:product"

add_recipe:
    path: "recipe/"
    controller: "AppBundle:Add:recipe"