message_discuss:
  path: discuss/{id}
  controller: AppBundle:Message:discuss
  requirements:
    id: '\d+'

message_all:
  path: ""
  controller: AppBundle:Message:all

message_start_discuss:
  path: "start/{idReceiver}"
  controller: AppBundle:Message:startConversation
  requirements:
    idReceiver: '\d+'
