modify_blog:
    path: "blog/{id}"
    controller: "AppBundle:Modify:blog"
    requirements:
      id: '\d+'

modify_news:
    path: "news/{id}"
    controller: "AppBundle:Modify:news"
    requirements:
      id: '\d+'

modify_product:
    path: "product/{id}"
    controller: "AppBundle:Modify:product"
    requirements:
      id: '\d+'

modify_recipe:
    path: "recipe/{id}"
    controller: "AppBundle:Modify:recipe"
    requirements:
      id: '\d+'