services:
    fos_user.owner_manager:
        class: MyUserBundle\Model\OwnerManager
        arguments: ['@fos_user.util.password_updater', '@fos_user.util.canonical_fields_updater', '@fos_user.object_manager', 'AppBundle\Entity\Owner']

    my_user.register_confirmed.listener:
        class: MyUserBundle\Services\RegisterConfirmationListener
        arguments: ['@router', '@mailer', '@twig', '%mailer_user%']
        tags:
            - { name: kernel.event_subscriber }

